version: '3.8'

services:
  # PostgreSQL Container;
  postgres:
    image: postgres:13
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: initial-diagnosis-business-intelligence
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: database-development
